In [2]:
from sklearn import datasets

digits=datasets.load_digits()

In [3]:
features=digits.data

target=digits.target
target

array([0, 1, 2, ..., 8, 9, 8])

In [4]:
features[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [6]:
from sklearn.datasets import make_regression
# 선형 회귀에 많이 사용되는 make_regression 데이터 셋

features,target,coefficients=make_regression(n_samples=100,n_features=3,n_informative=3,n_targets=1,noise=0.0,coef=True,random_state=1)

In [7]:
print('Features Matrix\n',features[:3])
print('Target Vector\n',target[:3])

Features Matrix
 [[ 1.29322588 -0.61736206 -0.11044703]
 [-2.793085    0.36633201  1.93752881]
 [ 0.80186103 -0.18656977  0.0465673 ]]
Target Vector
 [-10.37865986  25.5124503   19.67705609]


In [8]:
from sklearn.datasets import make_classification
# 분류에 많이 사용되는 make_classification 데이터 셋

In [9]:
from sklearn.datasets import make_blobs
# 군집에 많이 사용되는 make_blobs 데이터 셋

In [11]:
import pandas as pd
# url="https://tinyurl.com/simulated_data"

dataframe=pd.read_csv("iflg.csv")

dataframe.head(2)

id first_name last_name gender
0   1    Rickert    Bownas      M
1   2     Marena   Warrier      F

In [16]:
dataframe=pd.read_csv("titanic.csv")
dataframe.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [18]:
dataframe

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [20]:
dataframe[(dataframe['Sex']=='female')&(dataframe['Age']>=65)]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [21]:
dataframe[dataframe['Age']>=65]

PassengerId  Survived  Pclass                                  Name  \
33            34         0       2                 Wheadon, Mr. Edward H   
54            55         0       1        Ostby, Mr. Engelhart Cornelius   
96            97         0       1             Goldschmidt, Mr. George B   
116          117         0       3                  Connors, Mr. Patrick   
280          281         0       3                      Duane, Mr. Frank   
456          457         0       1             Millet, Mr. Francis Davis   
493          494         0       1               Artagaveytia, Mr. Ramon   
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson   
672          673         0       2           Mitchell, Mr. Henry Michael   
745          746         0       1          Crosby, Capt. Edward Gifford   
851          852         0       3                   Svensson, Mr. Johan   

      Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
33   male  66.0      0      0  C.A. 24579  10.5000   NaN        S  
54   male  65.0      0      1      113509  61.9792   B30        C  
96   male  71.0      0      0    PC 17754  34.6542    A5        C  
116  male  70.5      0      0      370369   7.7500   NaN        Q  
280  male  65.0      0      0      336439   7.7500   NaN        Q  
456  male  65.0      0      0       13509  26.5500   E38        S  
493  male  71.0      0      0    PC 17609  49.5042   NaN        C  
630  male  80.0      0      0       27042  30.0000   A23        S  
672  male  70.0      0      0  C.A. 24580  10.5000   NaN        S  
745  male  70.0      1      1   WE/P 5735  71.0000   B22        S  
851  male  74.0      0      0      347060   7.7750   NaN        S

In [22]:
dataframe['Sex'].replace("female","Woman").head(2)

0     male
1    Woman
Name: Sex, dtype: object

In [24]:
dataframe.rename(columns={'Pclass':'Passenger Class','Sex':'Gender'}).head(2)

PassengerId  Survived  Passenger Class  \
0            1         0                3   
1            2         1                1   

                                                Name  Gender   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [25]:
import collections

column_names=collections.defaultdict(str)

for name in dataframe.columns:
    column_names[name]
    
column_names

defaultdict(str,
            {'PassengerId': '',
             'Survived': '',
             'Pclass': '',
             'Name': '',
             'Sex': '',
             'Age': '',
             'SibSp': '',
             'Parch': '',
             'Ticket': '',
             'Fare': '',
             'Cabin': '',
             'Embarked': ''})

In [28]:
dataframe=pd.read_csv("titanic.csv")

print('Maximum:',dataframe['Age'].max())
print('Minimum:',dataframe['Age'].min())
print('Mean:',dataframe['Age'].mean())
print('Sum:',dataframe['Age'].sum())
print('Count:',dataframe['Age'].count())

Maximum: 80.0
Minimum: 0.42
Mean: 29.69911764705882
Sum: 21205.17
Count: 714


In [29]:
dataframe.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [31]:
dataframe['Sex'].unique()

array(['male', 'female'], dtype=object)

In [33]:
dataframe['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [32]:
dataframe['Sex'].nunique()

2

In [34]:
dataframe=pd.read_csv("titanic.csv")
dataframe[dataframe['Age'].isnull()].head(2)

PassengerId  Survived  Pclass                          Name   Sex  Age  \
5             6         0       3              Moran, Mr. James  male  NaN   
17           18         1       2  Williams, Mr. Charles Eugene  male  NaN   

    SibSp  Parch  Ticket     Fare Cabin Embarked  
5       0      0  330877   8.4583   NaN        Q  
17      0      0  244373  13.0000   NaN        S

In [35]:
import numpy as np

dataframe['Sex']=dataframe['Sex'].replace('male',np.nan)

In [36]:
dataframe=pd.read_csv("titanic.csv")
dataframe.drop('Age',axis=1).head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    male      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female      1      0   

      Ticket     Fare Cabin Embarked  
0  A/5 21171   7.2500   NaN        S  
1   PC 17599  71.2833   C85        C

In [37]:
dataframe.drop(['Age','Sex'],axis=1).head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name  SibSp  Parch     Ticket  \
0                            Braund, Mr. Owen Harris      1      0  A/5 21171   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      1      0   PC 17599   

      Fare Cabin Embarked  
0   7.2500   NaN        S  
1  71.2833   C85        C

In [38]:
print("Number of Rows In the Original DataFrame:",len(dataframe))
print("Number of Rows After Duduping:",len(dataframe.drop_duplicates()))

Number of Rows In the Original DataFrame: 891
Number of Rows After Duduping: 891


In [40]:
dataframe.drop_duplicates(subset=['Sex'])

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [41]:
dataframe.drop_duplicates(subset=['Sex'],keep='last')

PassengerId  Survived  Pclass                                      Name  \
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [42]:
dataframe=pd.read_csv("titanic.csv")
dataframe

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [46]:
dataframe.drop_duplicates(subset=['Pclass'])

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C  
9      0     237736  30.0708   NaN        C

In [49]:
import numpy as np

time_index=pd.date_range('06/06/2017',periods=100000,freq='30S')

dataframe=pd.DataFrame(index=time_index)
dataframe['Sale_Amount']=np.random.randint(1,10,100000)
dataframe.resample('W').sum()

Sale_Amount
2017-06-11        86748
2017-06-18       100760
2017-06-25       101523
2017-07-02       100258
2017-07-09       100585
2017-07-16        10327

In [51]:
from sklearn import preprocessing

feature=np.array([[-500.5],[-100.1],[0],[100.1],[900.9]])

minmax_scale=preprocessing.MinMaxScaler(feature_range=(0,1))

scaled_feature=minmax_scale.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [52]:
from sklearn.covariance import EllipticEnvelope
from sklearn.datasets import make_blobs

features,_=make_blobs(n_samples=10,n_features=2,centers=1,random_state=1)

features[0,0]=10000
features[0,1]=10000

outlier_detector=EllipticEnvelope(contamination=.1)

outlier_detector.fit(features)

outlier_detector.predict(features)

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [53]:
houses = pd.DataFrame()
houses['Price'] = [534433, 392333, 293222, 4322032]
houses['Bathrooms'] = [2, 3.5, 2, 116]
houses['Square_Feet'] = [1500, 2500, 1500, 48000]

houses[houses['Bathrooms'] < 20]


houses["Outlier"] = np.where(houses["Bathrooms"] < 20, 0, 1)

houses["Log_Of_Square_Feet"] = [np.log(x) for x in houses["Square_Feet"]]

houses

Price  Bathrooms  Square_Feet  Outlier  Log_Of_Square_Feet
0   534433        2.0         1500        0            7.313220
1   392333        3.5         2500        0            7.824046
2   293222        2.0         1500        0            7.313220
3  4322032      116.0        48000        1           10.778956